// Writes src/version.ts from package.json's version, so there is one place to
// bump instead of two. Run automatically by `npm version <bump>` (the "version"
// script below) and by `npm run build`, so the published SDK_VERSION always
// matches package.json even if someone forgets to run this by hand.
import { readFileSync, writeFileSync } from 'node:fs'

const pkg = JSON.parse(readFileSync('package.json', 'utf8')) as { version: string }

writeFileSync(
  'src/version.ts',
  `// Generated by scripts/sync-version.ts from package.json's version. Do not edit by hand.
/** Version of this SDK/runtime. A pack's \`sdk.range\` is checked against it. */
export const SDK_VERSION = '${pkg.version}'
`,
)
