// Generated by scripts/sync-version.ts from package.json's version. Do not edit by hand.
/** Version of this SDK/runtime. A pack's `sdk.range` is checked against it. */
export const SDK_VERSION = '0.1.0'
